### ISSUE TITLE
Review Aave V2 Connector

### ISSUE THREAD

**Issue by emilianobonassi** [Idle-Labs/idle-contracts#6]
https://forum.dao.reviews/t/idle-finance-aave-v2-wrapper-review-ask/69

Below my reccomendations

1. Use the property [underlying_asset_address](https://docs.aave.com/developers/the-core-protocol/atokens#underlying_asset_address)

https://github.com/Idle-Labs/idle-contracts/blob/3efe8fce6c8b12d4d272ae8af23a0b6c5f8cff11/contracts/wrappers/IdleAaveV2.sol#L44

to avoid misconfiguration at deploy time between token and respective underlying

2. Declare `_approveProvider()` as internal and remove onlyOwner modifier

https://github.com/Idle-Labs/idle-contracts/blob/3efe8fce6c8b12d4d272ae8af23a0b6c5f8cff11/contracts/wrappers/IdleAaveV2.sol#L50

It's only used once in the constructor. Consider to move the logic there.

3. Consider to declare pure functions

https://github.com/Idle-Labs/idle-contracts/blob/3efe8fce6c8b12d4d272ae8af23a0b6c5f8cff11/contracts/wrappers/IdleAaveV2.sol#L67

https://github.com/Idle-Labs/idle-contracts/blob/3efe8fce6c8b12d4d272ae8af23a0b6c5f8cff11/contracts/wrappers/IdleAaveV2.sol#L108

4. Replace `mul(100).div(10**9)` with `div(10**7)`

https://github.com/Idle-Labs/idle-contracts/blob/3efe8fce6c8b12d4d272ae8af23a0b6c5f8cff11/contracts/wrappers/IdleAaveV2.sol#L102

https://github.com/Idle-Labs/idle-contracts/blob/3efe8fce6c8b12d4d272ae8af23a0b6c5f8cff11/contracts/wrappers/IdleAaveV2.sol#L121

5. Consider changing variable names and pull based strategy instead of push during `mint()`. Avoid double balance check.

https://github.com/Idle-Labs/idle-contracts/blob/3efe8fce6c8b12d4d272ae8af23a0b6c5f8cff11/contracts/wrappers/IdleAaveV2.sol#L131-L141

Suggested change (no pull based)

```
  function mint()
    external onlyIdle
    returns (uint256 tokens) {
      uint256 tokens = IERC20(underlying).balanceOf(address(this));

      if (underlyingBalance != 0) {
        AaveLendingPoolV2 lendingPool = AaveLendingPoolV2(provider.getLendingPool());
        lendingPool.deposit(underlying, tokens, msg.sender, 29); // 29 -> referral
      }
           
      return tokens; 
}
```

You could consider to check null balancer in the caller, removing the `if` here.

6. Use `getNormalizedDebt` in `nextSupplyRate` to consider time difference between last reserve update and current block

https://github.com/Idle-Labs/idle-contracts/blob/3efe8fce6c8b12d4d272ae8af23a0b6c5f8cff11/contracts/wrappers/IdleAaveV2.sol#L88-L90

https://github.com/aave/protocol-v2/blob/ice/mainnet-deployment-03-12-2020/contracts/protocol/libraries/logic/ReserveLogic.sol#L85

or avoid gas optimizations and use `totalSupply` also for the VariableDebtToken

https://github.com/aave/protocol-v2/blob/ice/mainnet-deployment-03-12-2020/contracts/protocol/tokenization/VariableDebtToken.sol#L115

**Comment by bugduino** [comment]
Thanks Emiliano for the review, I incorporated most of the fixes [here](https://github.com/Idle-Labs/idle-contracts/commit/232c0dbfe3a56a83b43573fec390fccc01521b28).

Regarding the approve the ideal constructor should have been setup directly in this way:

```  
  constructor(address _token, address _addressesProvider, address _idleToken) public {
    require(_token != address(0), 'AAVE: addr is 0');
    token = _token;
    underlying = IAToken(_token).UNDERLYING_ASSET_ADDRESS();
    idleToken = _idleToken;
    provider = AaveLendingPoolProviderV2(_addressesProvider);
    IERC20(underlying).safeApprove(provider.getLendingPool(), uint256(-1));
  }
```
but if we move this line `IERC20(underlying).safeApprove(provider.getLendingPool(), uint256(-1));` in the constructor (or by moving it in a private / internal `_approveProvider`) and we try to recompile the contract (even with an empty build folder) with truffle, it hangs on and it just does not end the compilation @gravityblast took a look at it and may have more info, but that's why we moved it in a separate public method (and protected with onlyOwner and `!initialized`). If you have any clues about this 
would be helpful otherwise I think we can keep in in this way.

For the `pure` vs `view`, we are currently implementing the ILendingProtocol interface which 
requires them to be marked as `view`, it should not be a problem to set it to `pure` given that 
it's more strict but I'm getting this with 0.5.16 ` Overriding function changes state mutability from "view" to "pure"`
so given the min impact of this I would skip it.

For the `You could consider to check null balancer in the caller, removing the if here.`
I removed the check given that the only `mint()` call is made in the `IdleTokenGovernance`
here https://github.com/Idle-Labs/idle-contracts/blob/develop/contracts/IdleTokenGovernance.sol#L916-L922 
and the check is already performed.

**Comment by emilianobonassi** [comment]
I see thanks for explaining the constructor issue. It's strange anyway it's a suggestion, we can address the improvements in a further release.

LGTM, closing the issue 🤝

**Comment by emilianobonassi** [comment]
Great LGTM! :handshake:
